### ISSUE TITLE
Rename 'pinv' to 'inv'

### ISSUE THREAD

**Issue by gha3mi** [gha3mi/forinv#4]
@zoziha, what do you think about renaming `pinv` function to `inv` to generalize the function, which can essentially calculate the inverse and pseudo-inverse of a matrix?

**Comment by zoziha** [comment]
@gha3mi, I think both `pinv` and `inv` are fine.
When using the `inv` name, just describe in the README that this routine can compute pseudo-inverse and inverse matrices.
